### ISSUE TITLE
Publish packages with Pulumiverse naming

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-statuscake#1]
Hello @jgautheron,

All the providers in the Pulumiverse community are consistently published hinting at Pulumiverse in the package naming. This provides consistency & credibility to the users of all the providers.

May I ask to align the statuscake provider on these guidelines too? We have documented what you need to update here:

https://github.com/pulumiverse/infra#package-registries

We will set you up with Github Actions credentials for package publishing to work smoothly.

**Comment by ringods** [comment]
@jgautheron FYI I have equipped your repo with the proper GHA secrets to publish the various language packages.

**Comment by jgautheron** [comment]
Thanks @ringods 
I'm getting a missing GH token here: https://github.com/pulumiverse/pulumi-statuscake/actions/runs/3758726314/jobs/6387410299 should I rename it, or use the GH default one?

```
GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
```

**Comment by ringods** [comment]
Add this to the `release` workflow and you automatically have a `GITHUB_TOKEN` with write permissions on your repo (including GH releases):

https://github.com/pulumiverse/pulumi-aquasec/blob/main/.github/workflows/release.yaml#L7-L8

**Comment by jgautheron** [comment]
https://github.com/pulumiverse/pulumi-statuscake/pull/3

**Comment by ringods** [comment]
@jgautheron FYI starting next week, I'll be off for a few weeks, but feel free to involve @dirien in upcoming PRs. 😉

**Comment by ringods** [comment]
First release is available. I also created the required PR to list it in the [Pulumi Registry](https://www.pulumi.com/registry/):

https://github.com/pulumi/registry/pull/2028
