### ISSUE TITLE
Fix link to the Go SDK in installation instructions

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-statuscake#6]
Hello @jgautheron,

The link to the Go SDK of this provider in [`docs/installation-configuration.md`](https://github.com/pulumiverse/pulumi-statuscake/blob/main/docs/installation-configuration.md) renders a 404 error.

These files are copied over to the Pulumi `registry` repo on each release. We currently removed that link in our copy because these 404 errors impact our SEO:

https://github.com/pulumi/registry/pull/2322/files#diff-27f771da49cc6faccca446cbe1c454f69201a675390e6f003794e5f31e5bee2a

Can you fix the link and create a new release of this provider?

**Comment by jgautheron** [comment]
https://github.com/pulumiverse/pulumi-statuscake/pull/7
